import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
  index("routes/landing/landing.tsx"),
  route("signin", "routes/auth/signin.tsx"),
  route("signup", "routes/auth/signup.tsx"),
  route("feedback", "routes/dashboard/feedback.tsx"),
  route("test", "routes/test.tsx"),
  layout("layouts/app-layout.tsx", [
    route(":orgSlug", "routes/dashboard/dashboard.tsx", { index: true }),
    // Credentials — Library (staff + admin)
    route(":orgSlug/credentials", "routes/credentials/credentials.tsx"),
    route(":orgSlug/credentials/collections", "routes/credentials/collections-redirect.tsx"),
    route(":orgSlug/credentials/collections/:collectionRelId", "routes/credentials/collection-rel-detail.tsx"),
    route(":orgSlug/credentials/badges", "routes/credentials/badges-redirect.tsx"),
    route(":orgSlug/credentials/badges/:badgeRelId", "routes/credentials/badge-rel-detail.tsx"),
    // Credentials — Catalog (admin only)
    route(":orgSlug/credentials/catalog", "routes/credentials/catalog/catalog.tsx"),
    route(":orgSlug/credentials/catalog/collections/:collectionId", "routes/credentials/catalog/catalog-collection-detail.tsx"),
    route(":orgSlug/credentials/catalog/badges/:badgeId", "routes/credentials/catalog/catalog-badge-detail.tsx"),
    // Credentials — Analytics (admin only)
    route(":orgSlug/credentials/analytics", "routes/credentials/analytics/analytics.tsx"),
    route(":orgSlug/credentials/analytics/collections/:collectionRelId", "routes/credentials/analytics/analytics-collection.tsx"),
    route(":orgSlug/credentials/analytics/badges/:badgeRelId", "routes/credentials/analytics/analytics-badge.tsx"),
    // Credentials — Programs (staff + admin; create/edit admin only)
    route(":orgSlug/credentials/programs", "routes/credentials/programs/programs.tsx"),
    route(":orgSlug/credentials/programs/new", "routes/credentials/programs/program-new.tsx"),
    route(":orgSlug/credentials/programs/:programId", "routes/credentials/programs/program-detail.tsx"),
    route(":orgSlug/credentials/programs/:programId/edit", "routes/credentials/programs/program-edit.tsx"),
    route(":orgSlug/learners", "routes/learners/learners.tsx"),
    route(":orgSlug/learners/cohorts", "routes/learners/cohorts-redirect.tsx"),
    route(":orgSlug/learners/cohorts/new", "routes/learners/cohort-new.tsx"),
    route(":orgSlug/learners/cohorts/:cohortSlug", "routes/learners/cohort-detail.tsx"),
    route(":orgSlug/learners/invite", "routes/learners/invite.tsx"),
    route(":orgSlug/learners/:learnerId", "routes/learners/learner-detail.tsx"),
    route(":orgSlug/organization", "routes/organization/organization.tsx"),
    route(":orgSlug/organization/staff", "routes/organization/staff.tsx"),
    route(":orgSlug/organization/settings", "routes/organization/settings.tsx"),
    route(":orgSlug/user/profile", "routes/profile/profile.tsx"),
    route(":orgSlug/user/settings", "routes/profile/settings.tsx"),
    route(":orgSlug/about", "routes/dashboard/about.tsx"),
    // Creator Studio
    route(":orgSlug/creator", "routes/creator/creator.tsx"),
    route(":orgSlug/creator/collections", "routes/creator/collections.tsx"),
    route(":orgSlug/creator/collections/new", "routes/creator/collection-new.tsx"),
    route(":orgSlug/creator/collections/:collectionId", "routes/creator/collection-detail.tsx"),
    route(":orgSlug/creator/collections/:collectionId/edit", "routes/creator/collection-edit.tsx"),
    route(":orgSlug/creator/collections/:collectionId/submission", "routes/creator/collection-submission.tsx"),
    route(":orgSlug/creator/collections/:collectionId/badges/:badgeId", "routes/creator/badge-detail.tsx"),
    route(":orgSlug/creator/badges/:badgeId/edit", "routes/creator/badge-edit.tsx"),
    route(":orgSlug/creator/authorizations", "routes/creator/authorizations.tsx"),
    route(":orgSlug/creator/authorizations/:requestId", "routes/creator/authorization-detail.tsx"),
    route(":orgSlug/creator/analytics", "routes/creator/analytics.tsx"),
    route(":orgSlug/creator/analytics/collections/:collectionId", "routes/creator/analytics-collection.tsx"),
    route(":orgSlug/creator/analytics/badges/:badgeId", "routes/creator/analytics-badge.tsx"),
    route(":orgSlug/creator/settings", "routes/creator/creator-settings.tsx"),
  ]),
] satisfies RouteConfig;
