import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
  index("routes/landing/landing.tsx"),
  route("signin", "routes/auth/signin.tsx"),
  route("signup", "routes/auth/signup.tsx"),
  route("feedback", "routes/dashboard/feedback.tsx"),
  route("test", "routes/test.tsx"),
  layout("layouts/app-layout.tsx", [
    route(":orgSlug", "routes/dashboard/dashboard.tsx", { index: true }),
    route(":orgSlug/credentials", "routes/credentials/credentials.tsx"),
    route(":orgSlug/credentials/collections", "routes/credentials/collections.tsx"),
    route(":orgSlug/credentials/browse", "routes/credentials/browse.tsx"),
    route(":orgSlug/credentials/create", "routes/credentials/create.tsx"),
    route(":orgSlug/credentials/collections/:collectionId", "routes/credentials/detail.tsx"),
    route(":orgSlug/credentials/collections/:collectionId/:badgeId", "routes/credentials/badge-detail.tsx"),
    route(":orgSlug/credentials/programs", "routes/credentials/programs/programs.tsx"),
    route(":orgSlug/credentials/programs/:programSlug", "routes/credentials/programs/program-detail.tsx"),
    route(":orgSlug/learners", "routes/learners/learners.tsx"),
    route(":orgSlug/learners/cohorts", "routes/learners/cohorts.tsx"),
    route(":orgSlug/learners/cohorts/:cohortSlug", "routes/learners/cohort-detail.tsx"),
    route(":orgSlug/learners/add", "routes/learners/add.tsx"),
    route(":orgSlug/learners/:learnerId", "routes/learners/learner-detail.tsx"),
    route(":orgSlug/organization", "routes/organization/organization.tsx"),
    route(":orgSlug/organization/staff", "routes/organization/staff.tsx"),
    route(":orgSlug/organization/settings", "routes/organization/settings.tsx"),
    route(":orgSlug/user/profile", "routes/profile/profile.tsx"),
    route(":orgSlug/user/settings", "routes/profile/settings.tsx"),
    route(":orgSlug/about", "routes/dashboard/about.tsx"),
    // Creator Studio
    route(":orgSlug/creator", "routes/creator/creator.tsx"),
    route(":orgSlug/creator/collections", "routes/creator/collections.tsx"),
    route(":orgSlug/creator/collections/new", "routes/creator/collection-new.tsx"),
    route(":orgSlug/creator/collections/:collectionId", "routes/creator/collection-detail.tsx"),
    route(":orgSlug/creator/collections/:collectionId/edit", "routes/creator/collection-edit.tsx"),
    route(":orgSlug/creator/collections/:collectionId/submission", "routes/creator/collection-submission.tsx"),
    route(":orgSlug/creator/collections/:collectionId/badges/:badgeId", "routes/creator/badge-detail.tsx"),
    route(":orgSlug/creator/badges/:badgeId/edit", "routes/creator/badge-edit.tsx"),
    route(":orgSlug/creator/authorizations", "routes/creator/authorizations.tsx"),
    route(":orgSlug/creator/authorizations/:requestId", "routes/creator/authorization-detail.tsx"),
    route(":orgSlug/creator/analytics", "routes/creator/analytics.tsx"),
    route(":orgSlug/creator/analytics/collections/:collectionId", "routes/creator/analytics-collection.tsx"),
    route(":orgSlug/creator/analytics/badges/:badgeId", "routes/creator/analytics-badge.tsx"),
    route(":orgSlug/creator/settings", "routes/creator/creator-settings.tsx"),
  ]),
] satisfies RouteConfig;
